[package]
name = "spanner-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http.workspace = true
tokio = { workspace = true, features = ["signal", "time", "fs", "macros"] }
gcp-auth-channel = { path = "../../gcp-auth-channel", features = ["channel"] }

protos = { path = "../../protos", features = ["spanner"] }
serde = { workspace = true, features = ["derive"] }
timestamp = { path = "../../timestamp" }
prost = { workspace = true }
tonic = { workspace = true, features = ["transport"] }
futures.workspace = true
thiserror.workspace = true
pin-project-lite.workspace = true
net-utils = { path = "../../net-utils" }
tracing.workspace = true
uuid.workspace = true
itoa.workspace = true
longrunning = { path = "../../longrunning" }
http-body.workspace = true
serde_json = { workspace = true, optional = true }
shared.workspace = true
spanner-rs-macros = { path = "../spanner-rs-macros" }
tower = { workspace = true, features = ["retry"] }
base64 = "0.21.0"
bytes.workspace = true
anyhow = "1"
path-aware-serde = { path = "../../path-aware-serde", features = [
    "json",
    "serde_json",
] }
paste.workspace = true
typenum.workspace = true
tokio-util.workspace = true
fxhash = "0.2.1"
generic-array = "1.2.0"
bytemuck = { version = "1.22.0", features = ["derive", "extern_crate_alloc"] }

# debug-macro = { path = "../../../../debug-macro" }

[dev-dependencies]
rand.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
ryu = "1.0.12"


[features]
default = []                                                               # ["serde_json", "admin", "emulator"]
serde_json = ["dep:serde_json"]
admin = ["protos/spanner-admin-database", "protos/spanner-admin-instance"]
emulator = ["tokio/process", "gcp-auth-channel/emulator"]
debug-table-macro = []
