[package]
name = "google-sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
# data-structures = { version = "0.0.0", path = "../../data-structures" }
peg = "0.8.2"
phf = { version = "0.11.1", features = ["macros", "unicase"] }
serde_json.workspace = true
thiserror.workspace = true
timestamp = { path = "../../timestamp" }
unicase = "2.6.0"
