[package]
name = "serde-helpers"
version.workspace = true
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compact_str = { version = "0.6.0", features = ["serde", "bytes"] }
serde.workspace = true
deepsize = { version = "0.2.0", features = ["derive", "smallvec"], optional = true }
tracing.workspace = true
smallvec.workspace = true


[features]
deepsize = ["dep:deepsize"]
