[package]
name = "timestamp"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.1.3", optional = true }
chrono = { version = "0.4.19", features = ["alloc", "serde"] }
num-integer = { version = "0.1.44", features = [
    "i128",
    "std",
], default-features = false }
num-traits = { version = "0.2.15", features = ["i128"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
itoa.workspace = true
time = { workspace = true, features = [
    "macros",
    "quickcheck",
    "serde-human-readable",
] }
deepsize = { version = "0.2.0", optional = true }

tracing = { workspace = true }

prost = { workspace = true, optional = true }
prost-types = { version = "0.11", optional = true }
chrono-tz = "0.8.1"
schemars = { version = "0.8.11", optional = true, features = ["chrono"] }
rand = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.5.1"
rand.workspace = true
time = { workspace = true, features = ["rand"] }

[features]
default = ["rand", "deepsize", "arbitrary", "prost"]
deepsize = ["dep:deepsize"]
rand = ["dep:rand"]
arbitrary = ["dep:arbitrary"]
prost = ["dep:prost", "dep:prost-types"]
schemars = ["dep:schemars"]
