[package]
name = "timestamp-tz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.1", features = ["macros"] }


[build-dependencies]
parse-zoneinfo = "0.3"
tar = "0.4"
flate2 = "1.0"
anyhow = "1.0"
phf_codegen = "0.11.1"